### ISSUE TITLE
Can't find community.greengrass.jupyterlab and community.greengrass.libffi

### ISSUE THREAD

**Issue by flycast** [awslabs/aws-greengrass-labs-jupyterlab#2]
I am real excited to try out jupyterlab with greengrass to aid developing python scripts in custom components. The directions don't make sense to me though. In the read me it says:

 > You need to upload both community.greengrass.jupyterlab and community.greengrass.libffi to your account, but you need to include only community.greengrass.jupyterlab in your deployments.

I can't find either file here or by searching google.

When I look at the configuration files I think perhaps I don't need to upload anything, that the configuration installs everything needed using the lifecycle part of the configuration.

I think I am not understanding something here.

**Comment by massi-ang** [comment]
Hi Eric,

thanks for your interest in using this component. I realize the README is not clear enough in regards on how to upload those component. We will work to provide clearer instructions. In the meanwhile please have a look at the instructions provided in [BUILD.md](https://github.com/awslabs/aws-greengrass-labs-jupyterlab/blob/main/BUILD.md)

**Comment by ahmedmuzammilAI** [comment]
here's the solution to your issue @flycast 
step1: you need to build an individual component for [aws.greengrass.labs.libffi.yaml](https://github.com/awslabs/aws-greengrass-labs-jupyterlab/blob/main/recipes/aws.greengrass.labs.libffi.yaml) using the yaml file provided in the recipes folder.

step2: build the main jupyterlab lap component [aws.greengrass.labs.jupyterlab.yaml](https://github.com/awslabs/aws-greengrass-labs-jupyterlab/blob/main/recipes/aws.greengrass.labs.jupyterlab.yaml) using the other yaml file provided in the same folder.

step3: create a deployment and select these two components together and then deploy.

Also make sure your core device has python3 and venv already installed.

**Comment by massi-ang** [comment]
Added clarifications to the README on how to build the component
